name: Android Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      # 解码并保存 Keystore 文件
      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -d > app/release.keystore

      # 设置签名环境变量
      - name: Set up keystore properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "storeFile=release.keystore" > keystore.properties
          echo "storePassword=$KEYSTORE_PASSWORD" >> keystore.properties
          echo "keyAlias=$KEY_ALIAS" >> keystore.properties
          echo "keyPassword=$KEY_PASSWORD" >> keystore.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APKs
        run: ./gradlew assembleRelease

      # 上传所有相关的 Release APKs (兼容单/多 APK)
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
#        下面这句在 on: release: types: [created] 条件下是多余的，因为 Release 创建必然与一个标签相关联。
#        if: startsWith(github.ref, 'refs/tags/')
        with:
          # 使用多行输入来指定多个文件匹配模式
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/app-*-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
